[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
   package = 'netlify-plugin-contextual-env'

[context.dev]
    command = "npm run build"

[context.staging]
    command = "npm run build:staging"

[context.prod]
    command = "npm run build:prod"

